baseURL: http://example.org/
languageCode: en-us
title: mi portforio
theme: porthogo
author: 
  facebook: "https://www.facebook.com/profile.php?id=100008299605005" 
  twitter: "https://twitter.com/example" 
  email: "contact@example.org" 
  name: "Acme Corporation" 
  location: Zaragoza
  phone: (999) 999-9999 
  hours: "**Lunes-Viernes** 9:00AM - 6:00PM" 

menu:
  main: 
    - identifier: about 
      name: Acerca de 
      url: /about 
      weight: 100 
    - identifier: sobemi_trabjo
      name: sobemi_trabjo
      url: /sobemi_trabjo
      weight: 200 
    - identifier: miproyecto
      name: miproyecto
      url: /miproyecto 
      weight: 300 
    - identifier: contact
      name: Contacto 
      url: /contacto 
      weight: 400 
params:
  plugins:
    css:
      - link: >-
          https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css
      - link: 'https://pro.fontawesome.com/releases/v5.10.0/css/all.css'
      - link: >-
          https://cdnjs.cloudflare.com/ajax/libs/hover.css/2.1.0/css/hover-min.css
      - link: >-
          https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap
      - link: plugins/text-animation/text-animation.css
      - link: plugins/hugrid/hugrid.css
    js:
      - link: 'https://code.jquery.com/jquery-3.5.1.min.js'
      - link: >-
          https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.js
      - link: plugins/text-animation/text-animation.js
      - link: plugins/hugrid/hugrid.min.js
  logo_light: images/logo.svg
  logo_dark: images/logo-dark.svg
  copyright: (c) Mohamed 
  description: Personal Portfolio
  author: Burton Guster
  favicon: images/favicon.png
  preloader:
    enable: true
    preloader: images/preloader.gif